#!/usr/bin/env python3
import os, sys
import subprocess
from preprocessor.preprocessor import Preprocessor

def preprocess_and_run(censeo_path):
    prec = Preprocessor()
    prec.set_file_path(censeo_path)
    prec.run()
    subprocess.call(["python3", censeo_path + "_out"], env=os.environ)

if __name__ == "__main__":
    path = sys.argv[1]
    preprocess_and_run(path)
    
